// src/commands/v2/auto-flow.ts
//
// Auto track: extract HTTP surface deterministically, prompt for base URL,
// push endpoints to synapse-ui-backend as an MCP server config, and print
// the runner block the user pastes into their MCP client.
//
// No code is emitted into the user's repo.

import path from "node:path";
import { input } from "@inquirer/prompts";
import type { HttpEndpoint, SurfaceManifest } from "../../extractors/core/surface-manifest.js";
import { pickEndpoints } from "./endpoint-picker.js";
import {
  createMcpServer,
  batchCreateEndpoints,
  UiBackendError,
  type UiEndpointCreate,
} from "../../backend/ui-client.js";
import { t, stepOk, stepInfo } from "../../ui/theme.js";
import { roundedBox } from "../../ui/box.js";
import { Spinner } from "../../ui/spinner.js";

const BASE_URL_VAR = "ENDPOINT_BASE_URL";
const BASE_URL_PLACEHOLDER = "<your-app-deployed-url>";

/** Convert a suggested_tool_name (snake_case) to a display Name Case. */
function toDisplayName(snake: string): string {
  return snake
    .split("_")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function endpointToUi(e: HttpEndpoint): UiEndpointCreate {
  // ui-backend rejects PATCH — coerce to POST (semantically closest).
  const method = e.method === "PATCH" ? "POST" : e.method;
  return {
    name: toDisplayName(e.suggested_tool_name),
    description: e.description || `${e.method} ${e.path}`,
    method,
    url: `\${${BASE_URL_VAR}}${e.path}`,
    headers: e.headers_hint.map((h) => ({ key: h.key, value: h.value })),
    payload: e.payload_example,
  };
}

export interface AutoFlowOptions {
  workingDir: string;
  manifest: SurfaceManifest;
  serverName?: string; // if omitted, derives from workingDir basename
  baseUrl?: string; // if provided (--base-url flag), skips the prompt
  /** Session id (from SessionManager) — echoed in the success footer so
   *  users can quote it when reporting an issue. */
  sessionId?: string;
  /** --smart-names: have the backend read handler source (+ readme context)
   *  and name/describe tools from real behavior instead of route + docstring
   *  alone. Runs server-side (billed) — nothing changes on the CLI's own
   *  compute, only the request sent to synapse-ui-backend/grpc.synaps3.ai. */
  smartNames?: boolean;
}

export async function runAutoFlow(opts: AutoFlowOptions): Promise<void> {
  const endpoints = opts.manifest.endpoints;

  if (endpoints.length === 0) {
    roundedBox("No Endpoints Found", "⚠", t.warn, [
      "The extractor didn't find any HTTP route decorators.",
      "",
      "Try:",
      "  " + t.cmd("synapse build --custom") + " — compose internal functions",
      "  " + t.cmd("synapse build --auto --entry <file>") + " — point at a file (planned)",
    ]);
    return;
  }

  stepInfo(
    "Detected",
    `${endpoints.length} endpoint${endpoints.length === 1 ? "" : "s"} (${opts.manifest.framework ?? "unknown framework"})`,
  );

  let selected = await pickEndpoints(endpoints);
  if (selected.length === 0) {
    stepInfo("No endpoints selected", "aborting");
    return;
  }

  if (opts.smartNames) {
    selected = await maybeNameEndpoints(selected, opts);
  }

  const baseUrl =
    opts.baseUrl ??
    (
      await input({
        message: "Where is this API deployed? (leave blank to set later via env)",
        default: "",
      })
    ).trim();

  const serverName = opts.serverName ?? path.basename(opts.workingDir);
  const description = `Generated by Synapse from ${opts.manifest.framework ?? "detected"} project`;

  let serverId: string;
  try {
    const created = await createMcpServer({
      name: serverName,
      description,
      workingDir: opts.workingDir,
    });
    serverId = created.server.id;
  } catch (err) {
    const detail = err instanceof UiBackendError ? err.detail : String(err);
    roundedBox("Server Create Failed", "✖", t.err, [detail]);
    return;
  }

  try {
    await batchCreateEndpoints({
      serverId,
      endpoints: selected.map(endpointToUi),
      workingDir: opts.workingDir,
      partial: opts.manifest.partial === true,
    });
  } catch (err) {
    const detail = err instanceof UiBackendError ? err.detail : String(err);
    roundedBox("Endpoint Upload Failed", "✖", t.err, [detail]);
    return;
  }

  stepOk("Uploaded", `server_id = ${serverId}`);

  const runnerEnv: Record<string, string> = {
    SYNAPSE_SERVER_ID: serverId,
    SYNAPSE_API_KEY: "<your key>",
    [BASE_URL_VAR]: baseUrl || BASE_URL_PLACEHOLDER,
  };

  // Additional secrets the endpoints referenced (e.g. ${AUTH_TOKEN}).
  const extraVars = new Set<string>();
  for (const e of selected) {
    for (const h of e.headers_hint) {
      const m = h.value.match(/\$\{([A-Z_][A-Z0-9_]*)\}/);
      if (m && m[1] !== BASE_URL_VAR) extraVars.add(m[1]);
    }
  }
  for (const v of extraVars) runnerEnv[v] = "<paste your value>";

  const runnerBlock = {
    mcpServers: {
      [serverName]: {
        command: "npx",
        args: ["-y", "@2ndbrainlabs-ai/synapse-mcp"],
        env: runnerEnv,
      },
    },
  };

  console.log();
  console.log("  " + t.dim("Add this to your MCP client config:"));
  console.log();
  for (const line of JSON.stringify(runnerBlock, null, 2).split("\n")) {
    console.log("    " + t.subtle(line));
  }
  console.log();
  if (opts.sessionId) {
    stepInfo("Session", `${opts.sessionId}  ${t.dim("— quote this when reporting an issue")}`);
  }
  stepOk("Done");
}

/**
 * --smart-names, hosted: sends handler source (+ readme context) to the
 * backend's NameEndpointsRequest RPC so it can read the code and return an
 * agent-legible tool_name + description per endpoint. The LLM call itself
 * runs server-side (billed/monetized) — only the request payload changes
 * here. Falls back to the mechanical suggested_tool_name/description (per
 * endpoint, or entirely) on any failure.
 */
async function maybeNameEndpoints(
  endpoints: HttpEndpoint[],
  opts: AutoFlowOptions,
): Promise<HttpEndpoint[]> {
  const spinner = new Spinner("orbital");
  spinner.start("Naming tools from handler source");
  try {
    const { buildEndpointContexts } = await import("../../backend/endpoint-namer.js");
    const { readRepoContext } = await import("../../backend/repo-context.js");
    const { makeSynapseClient } = await import("../../grpc/client-factory.js");

    const client = makeSynapseClient({ effectiveMode: "hosted", workingDir: opts.workingDir });
    const contexts = buildEndpointContexts(endpoints, opts.workingDir);
    const result = await client.nameEndpoints({
      endpoints: contexts,
      workingDir: opts.workingDir,
      readmeContext: readRepoContext(opts.workingDir),
      sessionId: opts.sessionId,
    });

    if (!result.success) {
      spinner.fail("Naming pass failed", result.error || "using route-derived names instead");
      return endpoints;
    }

    spinner.complete(`Named ${result.names.length}/${endpoints.length} tool(s) from source`);
    const byIndex = new Map(result.names.map((n) => [n.index, n]));
    return endpoints.map((ep, i) => {
      const named = byIndex.get(i);
      if (!named) return ep;
      return { ...ep, suggested_tool_name: named.tool_name, description: named.description };
    });
  } catch {
    spinner.fail("Naming pass failed", "using route-derived names instead");
    return endpoints;
  }
}
