// src/commands/v2/auto-flow.ts
//
// Auto track: extract HTTP surface deterministically, prompt for base URL,
// push endpoints to synapse-ui-backend as an MCP server config, and print
// the runner block the user pastes into their MCP client.
//
// No code is emitted into the user's repo.

import path from "node:path";
import { input } from "@inquirer/prompts";
import type { HttpEndpoint, SurfaceManifest } from "../../extractors/core/surface-manifest.js";
import { pickEndpoints } from "./endpoint-picker.js";
import {
  createMcpServer,
  batchCreateEndpoints,
  UiBackendError,
  type UiEndpointCreate,
} from "../../backend/ui-client.js";
import { t, stepOk, stepInfo } from "../../ui/theme.js";
import { roundedBox } from "../../ui/box.js";

const BASE_URL_VAR = "ENDPOINT_BASE_URL";
const BASE_URL_PLACEHOLDER = "<your-app-deployed-url>";

/** Convert a suggested_tool_name (snake_case) to a display Name Case. */
function toDisplayName(snake: string): string {
  return snake
    .split("_")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function endpointToUi(e: HttpEndpoint): UiEndpointCreate {
  // ui-backend rejects PATCH — coerce to POST (semantically closest).
  const method = e.method === "PATCH" ? "POST" : e.method;
  return {
    name: toDisplayName(e.suggested_tool_name),
    description: e.description || `${e.method} ${e.path}`,
    method,
    url: `\${${BASE_URL_VAR}}${e.path}`,
    headers: e.headers_hint.map((h) => ({ key: h.key, value: h.value })),
    payload: e.payload_example,
  };
}

export interface AutoFlowOptions {
  workingDir: string;
  manifest: SurfaceManifest;
  serverName?: string; // if omitted, derives from workingDir basename
  baseUrl?: string; // if provided (--base-url flag), skips the prompt
}

export async function runAutoFlow(opts: AutoFlowOptions): Promise<void> {
  const endpoints = opts.manifest.endpoints;

  if (endpoints.length === 0) {
    roundedBox("No Endpoints Found", "⚠", t.warn, [
      "The extractor didn't find any HTTP route decorators.",
      "",
      "Try:",
      "  " + t.cmd("synapse build --custom") + " — compose internal functions",
      "  " + t.cmd("synapse build --auto --entry <file>") + " — point at a file (planned)",
    ]);
    return;
  }

  stepInfo(
    "Detected",
    `${endpoints.length} endpoint${endpoints.length === 1 ? "" : "s"} (${opts.manifest.framework ?? "unknown framework"})`,
  );

  const selected = await pickEndpoints(endpoints);
  if (selected.length === 0) {
    stepInfo("No endpoints selected", "aborting");
    return;
  }

  const baseUrl =
    opts.baseUrl ??
    (
      await input({
        message: "Where is this API deployed? (leave blank to set later via env)",
        default: "",
      })
    ).trim();

  const serverName = opts.serverName ?? path.basename(opts.workingDir);
  const description = `Generated by Synapse from ${opts.manifest.framework ?? "detected"} project`;

  let serverId: string;
  try {
    const created = await createMcpServer({
      name: serverName,
      description,
      workingDir: opts.workingDir,
    });
    serverId = created.server.id;
  } catch (err) {
    const detail = err instanceof UiBackendError ? err.detail : String(err);
    roundedBox("Server Create Failed", "✖", t.err, [detail]);
    return;
  }

  try {
    await batchCreateEndpoints({
      serverId,
      endpoints: selected.map(endpointToUi),
      workingDir: opts.workingDir,
      partial: opts.manifest.partial === true,
    });
  } catch (err) {
    const detail = err instanceof UiBackendError ? err.detail : String(err);
    roundedBox("Endpoint Upload Failed", "✖", t.err, [detail]);
    return;
  }

  stepOk("Uploaded", `server_id = ${serverId}`);

  const runnerEnv: Record<string, string> = {
    SYNAPSE_SERVER_ID: serverId,
    SYNAPSE_API_KEY: "<your key>",
    [BASE_URL_VAR]: baseUrl || BASE_URL_PLACEHOLDER,
  };

  // Additional secrets the endpoints referenced (e.g. ${AUTH_TOKEN}).
  const extraVars = new Set<string>();
  for (const e of selected) {
    for (const h of e.headers_hint) {
      const m = h.value.match(/\$\{([A-Z_][A-Z0-9_]*)\}/);
      if (m && m[1] !== BASE_URL_VAR) extraVars.add(m[1]);
    }
  }
  for (const v of extraVars) runnerEnv[v] = "<paste your value>";

  const runnerBlock = {
    mcpServers: {
      [serverName]: {
        command: "npx",
        args: ["-y", "@2ndbrainlabs-ai/synapse-mcp"],
        env: runnerEnv,
      },
    },
  };

  console.log();
  console.log("  " + t.dim("Add this to your MCP client config:"));
  console.log();
  for (const line of JSON.stringify(runnerBlock, null, 2).split("\n")) {
    console.log("    " + t.subtle(line));
  }
  console.log();
}
