// src/backend/server-renderer.ts
//
// Deterministic Python renderer. TS template literal equivalent of the
// private Python backend's templates/python/mcp_server.j2 + server_renderer.py.
// No LLM — same ToolPlan → same output, byte-identical.

import { paramsSignature, type ToolPlan } from "./schemas.js";
import type { HttpEndpoint, SurfaceManifest } from "../extractors/core/surface-manifest.js";

function dedupOrdered(items: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of items) {
    if (item && !seen.has(item)) {
      seen.add(item);
      out.push(item);
    }
  }
  return out;
}

function escRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function containsCall(body: string, name: string): boolean {
  return new RegExp(`\\b${escRe(name)}\\s*\\(`).test(body);
}

function canonicalImports(plan: ToolPlan, manifest: SurfaceManifest): string[] {
  const llmImports = [...(plan.imports ?? [])];
  for (const fn of manifest.functions) {
    if (containsCall(plan.body_source, fn.qualname)) {
      llmImports.push(`from ${fn.module} import ${fn.qualname}`);
    }
  }
  return dedupOrdered(llmImports);
}

function indent(text: string, n: number): string {
  const pad = " ".repeat(n);
  return text
    .split("\n")
    .map((line) => (line.length ? pad + line : line))
    .join("\n");
}

function jsonQuote(s: string): string {
  return JSON.stringify(s);
}

export function renderPython(
  plan: ToolPlan,
  manifest: SurfaceManifest,
  mcpServerName: string,
): string {
  const description =
    plan.description || `MCP tool '${plan.tool_name}' composed by Synapse.`;
  const bodyRaw = plan.body_source.replace(/\s+$/, "") || 'return {"ok": True}';
  const bodyIndented = indent(bodyRaw, 4);
  const imports = canonicalImports(plan, manifest);
  const outputFilename = `${plan.tool_name}_server.py`;
  const asyncKw = plan.is_async ? "async " : "";
  const params = paramsSignature(plan);
  const importsBlock = imports.length ? imports.join("\n") + "\n" : "";

  return (
    `"""\n` +
    `${description}\n\n` +
    `Generated by Synapse (v2 Custom mode). Edit freely — you own this file.\n` +
    `Run:  python ${outputFilename}\n` +
    `"""\n` +
    `from __future__ import annotations\n\n` +
    `from mcp.server.fastmcp import FastMCP\n` +
    importsBlock +
    `\n` +
    `mcp = FastMCP("${mcpServerName}")\n\n\n` +
    `@mcp.tool(name="${plan.tool_name}", description=${jsonQuote(description)})\n` +
    `${asyncKw}def ${plan.tool_name}(${params}) -> dict:\n` +
    `${bodyIndented}\n\n\n` +
    `if __name__ == "__main__":\n` +
    `    mcp.run()\n`
  );
}

// -----------------------------------------------------------------------------
// Passthrough renderer — local `--auto` mode. Endpoints are already fully
// specified (method, path, headers, payload shape), so this is pure string
// templating: no LLM call, no shape/verify pass. One tool per endpoint that
// forwards the call to the real deployed API.
// -----------------------------------------------------------------------------

function sanitizeIdentifier(name: string): string {
  let s = name.trim().toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "");
  if (!s) s = "tool";
  if (/^[0-9]/.test(s)) s = `_${s}`;
  return s;
}

function extractPathParams(path: string): string[] {
  const out: string[] = [];
  const re = /\{([a-zA-Z_][a-zA-Z0-9_]*)\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(path))) out.push(m[1]);
  return out;
}

function extractBodyParams(payload: unknown): string[] {
  if (payload && typeof payload === "object" && !Array.isArray(payload)) {
    return Object.keys(payload as Record<string, unknown>);
  }
  return [];
}

interface RenderedEndpointTool {
  toolName: string;
  source: string;
  envVars: string[];
}

function renderEndpointTool(ep: HttpEndpoint, baseUrlVar: string, toolName: string): RenderedEndpointTool {
  const pathParams = extractPathParams(ep.path);
  const hasBody = !["GET", "DELETE"].includes(ep.method.toUpperCase());
  const bodyParams = hasBody ? extractBodyParams(ep.payload_example) : [];
  const allParams = dedupOrdered([...pathParams, ...bodyParams]);
  const paramsSig = allParams.map((p) => `${p}: Any = None`).join(", ");

  const envVars = new Set<string>([baseUrlVar]);
  const headerLines: string[] = [];
  for (const h of ep.headers_hint ?? []) {
    const m = h.value.match(/\$\{([A-Z_][A-Z0-9_]*)\}/);
    if (m) {
      envVars.add(m[1]);
      headerLines.push(`        ${jsonQuote(h.key)}: os.environ.get(${jsonQuote(m[1])}, "")`);
    } else {
      headerLines.push(`        ${jsonQuote(h.key)}: ${jsonQuote(h.value)}`);
    }
  }
  const headersBlock = headerLines.length
    ? `    headers = {\n${headerLines.join(",\n")}\n    }\n`
    : `    headers = {}\n`;

  const bodyLine = bodyParams.length
    ? `    payload = {${bodyParams.map((p) => `${jsonQuote(p)}: ${p}`).join(", ")}}\n`
    : "";

  const method = ep.method.toLowerCase();
  const requestArgs = ["url", "headers=headers"];
  if (bodyParams.length) requestArgs.push("json=payload");

  const description = ep.description || `${ep.method} ${ep.path}`;

  const body =
    `    url = f"{os.environ[${jsonQuote(baseUrlVar)}]}${ep.path}"\n` +
    headersBlock +
    bodyLine +
    `    resp = requests.${method}(${requestArgs.join(", ")})\n` +
    `    resp.raise_for_status()\n` +
    `    try:\n` +
    `        return resp.json()\n` +
    `    except ValueError:\n` +
    `        return {"status_code": resp.status_code, "text": resp.text}\n`;

  const source =
    `@mcp.tool(name=${jsonQuote(toolName)}, description=${jsonQuote(description)})\n` +
    `def ${toolName}(${paramsSig}) -> dict:\n` +
    body;

  return { toolName, source, envVars: Array.from(envVars) };
}

/** Ensures no two endpoints in the batch land on the same Python identifier. */
function dedupeToolNames(rawNames: string[]): string[] {
  const seen = new Map<string, number>();
  return rawNames.map((name) => {
    const count = seen.get(name) ?? 0;
    seen.set(name, count + 1);
    return count === 0 ? name : `${name}_${count + 1}`;
  });
}

export function renderPassthroughPython(
  endpoints: HttpEndpoint[],
  mcpServerName: string,
  baseUrlVar = "ENDPOINT_BASE_URL",
): { source: string; envVars: string[] } {
  const rawNames = endpoints.map((ep) =>
    sanitizeIdentifier(ep.suggested_tool_name || `${ep.method}_${ep.path}`),
  );
  const toolNames = dedupeToolNames(rawNames);
  const tools = endpoints.map((ep, i) => renderEndpointTool(ep, baseUrlVar, toolNames[i]));
  const envVars = dedupOrdered(tools.flatMap((t) => t.envVars));
  const toolsBlock = tools.map((t) => t.source).join("\n\n");

  const source =
    `"""\n` +
    `MCP server generated by Synapse (local auto mode) — passthrough HTTP tools.\n\n` +
    `Generated by Synapse. Edit freely — you own this file.\n` +
    `Set ${envVars.join(", ")} before running.\n` +
    `"""\n` +
    `from __future__ import annotations\n\n` +
    `import os\n` +
    `from typing import Any\n\n` +
    `import requests\n` +
    `from mcp.server.fastmcp import FastMCP\n\n` +
    `mcp = FastMCP("${mcpServerName}")\n\n\n` +
    `${toolsBlock}\n\n\n` +
    `if __name__ == "__main__":\n` +
    `    mcp.run()\n`;

  return { source, envVars };
}

export function render(
  plan: ToolPlan,
  manifest: SurfaceManifest,
  mcpServerName: string,
): { ext: string; source: string } {
  if (manifest.language === "python") {
    return { ext: "py", source: renderPython(plan, manifest, mcpServerName) };
  }
  throw new Error(
    `ServerRenderer does not yet support language=${manifest.language}. ` +
      "Local backend ships Python only for now.",
  );
}
